name: Update Payment Status Report

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'submissions/**.json' # Trigger only if JSON files in submissions change

jobs:
  update_report:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow the job to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      # Optional: Install dependencies if your script needs them
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate payment status report
        run: python src/generators/payment_status_generator.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update payment status reports"
          # Commit both the active status and paid status files
          file_pattern: "data/payment_status.md data/paid.md"
          # Use PAT for potentially stricter push permissions, mirroring update-on-merge.yml
          push_token: ${{ secrets.PAT_TOKEN }}
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          push_options: '--force' # Optional: Use force push if needed, be cautious
